env:
  JULIA_VERSION: "1.10.2"
  JULIA_MINOR_VERSION: "1.10"
  JULIA_PATH: /var/lib/buildkite-agent/julia
  DATADEPS_ALWAYS_ACCEPT: true

steps:
  - label: ":building_construction: :speedboat: gpu setup"
    key: "init_gpu"
    env:
      TEST_GROUP: "none"
    plugins:
      - JuliaCI/julia#v1:
          version: "1.10"
      - JuliaCI/julia-test#v1: ~
    agents:
      queue: Oceananigans
      architecture: GPU

  - label: ":building_construction: :rowboat: cpu setup"
    key: "init_cpu"
    env:
      TEST_GROUP: "none"
      CUDA_VISIBLE_DEVICES: "-1"
    plugins:
      - JuliaCI/julia#v1:
          version: "1.10"
      - JuliaCI/julia-test#v1:
          coverage: true
    agents:
      queue: Oceananigans
      architecture: CPU

  - label: ":speedboat: GPU unit tests"
    plugins:
      - JuliaCI/julia#v1:
          version: "1.10"
      - JuliaCI/julia-test#v1:
          update_registry: false
          coverage: false
    agents:
      queue: Oceananigans
      architecture: GPU
    depends_on: "init_gpu"
    notify:
      - github_commit_status:
          context: "GPU tests"
    if: !build.pull_request.draft

  - label: ":rowboat: CPU unit tests"
    env:
      CUDA_VISIBLE_DEVICES: "-1"
    plugins:
      - JuliaCI/julia#v1:
          version: "1.10"
      - JuliaCI/julia-test#v1:
          update_registry: false
          coverage: true
    agents:
      queue: Oceananigans
      architecture: CPU
    depends_on: "init_cpu"
    notify:
      - github_commit_status:
          context: "CPU tests"
    if: !build.pull_request.draft

  - label: ":docusaurus: Documentation"
    env:
      CUDA_VISIBLE_DEVICES: "-1"
      JULIA_DEBUG: "Documenter"
    plugins:
      - JuliaCI/julia#v1:
          version: "1.10"
    command: |
      - "julia --color=yes --project=docs/ docs/make.jl"
    agents:
      queue: Oceananigans
      architecture: CPU
    depends_on: "init_cpu"
    notify:
      - github_commit_status:
          context: "Documentation"
    if: !build.pull_request.draft
