env:
  JULIA_VERSION: "1.10.2"
  JULIA_MINOR_VERSION: "1.10"
  JULIA_PATH: /var/lib/buildkite-agent/julia
  DATADEPS_ALWAYS_ACCEPT: true

steps:
  - label: ":construction: setup julia"
    key: "init"
    plugins:
      - JuliaCI/julia#v1:
          version: "1.10"
    notify:
      - github_commit_status:
          context: "Setup test environment"

  - label: ":speedboat: GPU tests"
    depends_on: "init"
    plugins:
      - JuliaCI/julia-test#v1:
          update_registry: true
          coverage: false
    notify:
      - github_commit_status:
          context: "GPU tests"
    if: !build.pull_request.draft

  - label: ":rowboat: CPU tests"
    depends_on: "init"
    env:
      CUDA_VISIBLE_DEVICES: "-1"
    plugins:
      - JuliaCI/julia-test#v1:
          update_registry: true
          coverage: true
    notify:
      - github_commit_status:
          context: "CPU tests"
    if: !build.pull_request.draft

  - label: ":docusaurus: Documentation"
    depends_on: "init"
    env:
      CUDA_VISIBLE_DEVICES: "-1"
      JULIA_DEBUG: "Documenter"
    command: 
      - "julia --color=yes --project=docs/ -e 'using Pkg; Pkg.Registry.update(); Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'"
      - "julia --color=yes --project=docs/ docs/make.jl"
    notify:
      - github_commit_status:
          context: "Documentation"
    if: !build.pull_request.draft
