env:
  JULIA_VERSION: "1.9.4"
  JULIA_MINOR_VERSION: "1.9"
  JULIA_PATH: /var/lib/buildkite-agent/julia
  DATADEPS_ALWAYS_ACCEPT: true

steps:
  - label: ":building_construction: initialize environment"
    key: "init"
    commands: 
     - "wget -N -P $JULIA_PATH https://julialang-s3.julialang.org/bin/linux/x64/$JULIA_MINOR_VERSION/julia-$JULIA_VERSION-linux-x86_64.tar.gz"
     - "tar xf $JULIA_PATH/julia-$JULIA_VERSION-linux-x86_64.tar.gz -C $JULIA_PATH"
     - "$JULIA_PATH/julia-$JULIA_VERSION/bin/julia -O0 --color=yes --project -e 'using Pkg; Pkg.instantiate(; verbose=true)'"
     - "$JULIA_PATH/julia-$JULIA_VERSION/bin/julia -O0 --color=yes --project -e 'using Pkg; Pkg.build()'"
     - "$JULIA_PATH/julia-$JULIA_VERSION/bin/julia -O0 --color=yes --project -e 'using Pkg; Pkg.precompile()'"
     - "$JULIA_PATH/julia-$JULIA_VERSION/bin/julia -O0 --color=yes --project -e 'using Pkg; Pkg.status()'"
    notify:
      - github_commit_status:
          context: "Initialise enviroment"

  - label: ":speedboat: GPU unit tests"
    commands: 
     - "$JULIA_PATH/julia-$JULIA_VERSION/bin/julia -O0 --color=yes --project -e 'using Pkg; Pkg.test()'"
    depends_on: "init"
    notify:
      - github_commit_status:
          context: "GPU tests"
    
  - label: ":rowboat: CPU unit tests"
    env:
     CUDA_VISIBLE_DEVICES: "-1"
    commands: 
     - "$JULIA_PATH/julia-$JULIA_VERSION/bin/julia -O0 --color=yes --project -e 'using Pkg; Pkg.test()'"
    depends_on: "init"
    notify:
      - github_commit_status:
          context: "CPU tests"
    
  - label: ":docusaurus: Documentation"
    env:
      CUDA_VISIBLE_DEVICES: "-1"
      JULIA_DEBUG: "Documenter"
      TMPDIR: "/var/lib/buildkite-agent/tmp"
    commands:
      - "$JULIA_PATH/julia-$JULIA_VERSION/bin/julia --color=yes --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'"
      - "$JULIA_PATH/julia-$JULIA_VERSION/bin/julia --color=yes --project=docs/ docs/make.jl"
    depends_on: "init"
    notify:
      - github_commit_status:
          context: "Documentation"

  - wait: ~
    continue_on_failure: true
    
  - label: ":skeleton-dance: clean up environment"
    command: "rm -rf $JULIA_PATH"
    notify:
      - github_commit_status:
          context: "Clean up"
