abstract type AbstractSedimentBiogeochemistry end
abstract type AbstractContinuousFormSedimentBiogeochemistry <: AbstractSedimentBiogeochemistry end

const ACFSBGC = AbstractContinuousFormSedimentBiogeochemistry